apiVersion: v1
kind: ConfigMap
metadata:
  name:  project3-configMap
data:
  DB_NAME: "postgres"
  DB_USER: "myuser"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: project3-secret
type: Opaque
data:
  DB_PASSWORD: bXlwYXNzd29yZA==